### ISSUE TITLE
Setting Timestamp end time results in a crash.

### ISSUE THREAD

**Issue by Swan** [Lachee/discord-rpc-csharp#25]
Here's my code.

```cs
DiscordManager.Presence.Timestamps = new Timestamps()
{
     End = DateTime.UtcNow.AddSeconds(100)
};

DiscordManager.Client.SetPresence(DiscordManager.Presence);
```

Here's the exception being thrown when doing so.

```
ERR : Unhandled Exception: Newtonsoft.Json.JsonSerializationException
ERR : Error getting value from 'epochEnd' on 'DiscordRPC.Timestamps'.
ERR :    at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o)
   at DiscordRPC.RPC.Payload.ArgumentPayload.SetObject(Object obj)
   at DiscordRPC.RPC.Payload.ArgumentPayload..ctor(Object args, Int64 nonce)
   at DiscordRPC.RPC.Commands.PresenceCommand.PreparePayload(Int64 nonce)
   at DiscordRPC.RPC.RpcConnection.ProcessCommandQueue()
   at DiscordRPC.RPC.RpcConnection.MainLoop()

```

**Comment by Lachee** [comment]
Thanks, I will have a look today when I get a chance

**Comment by Lachee** [comment]
Fixed with latest commit. I had the End value reading for the Start value by mistake, which was null. Do a new build of the library and then try again please.

**Comment by Swan** [comment]
Yep, works like a charm. Thanks :+1:
